//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIFAModdingUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FIFAModdingUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The higher this value to worse Players are at defending (more dependant on attribute).
        /// </summary>
        internal static string ATTRIBUTE_10_WEIGHT_DESC {
            get {
                return ResourceManager.GetString("ATTRIBUTE_10_WEIGHT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower this value the more players use overhead kicks and quick spins/turns on the ball.
        /// </summary>
        internal static string ATTRIBUTE_2_WEIGHT_DESC {
            get {
                return ResourceManager.GetString("ATTRIBUTE_2_WEIGHT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower this value the more bad stand tacklers will use a standing tackle and be good at it.
        /// </summary>
        internal static string ATTRIBUTE_24_WEIGHT_DESC {
            get {
                return ResourceManager.GetString("ATTRIBUTE_24_WEIGHT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower this value the more bad slide tacklers will use slide tackle and be good at it (needs FORCE Fouling to really show in game).
        /// </summary>
        internal static string ATTRIBUTE_25_WEIGHT_DESC {
            get {
                return ResourceManager.GetString("ATTRIBUTE_25_WEIGHT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A higher value makes it very difficult to create chances and score.
        /// </summary>
        internal static string ContextEffectBallPosition {
            get {
                return ResourceManager.GetString("ContextEffectBallPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower this value the AI tends to dribble more.
        /// </summary>
        internal static string ContextEffectBallXZSpin {
            get {
                return ResourceManager.GetString("ContextEffectBallXZSpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower this value the AI tends to dribble more.
        /// </summary>
        internal static string ContextEffectBallYSpin {
            get {
                return ResourceManager.GetString("ContextEffectBallYSpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing ContextEffectDribbleKickAngle made it very difficult to play the AI (as a poor team) and ability of players meant more, the game was slower too.
        /// </summary>
        internal static string ContextEffectDribbleKickAngle {
            get {
                return ResourceManager.GetString("ContextEffectDribbleKickAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing ContextEffectDribblePressure caused more aggressive tackles. 
        ///Increasing ContextEffectDribblePressure causes the &quot;dribbler&quot; to be shoved off the ball more easily.
        /// </summary>
        internal static string ContextEffectDribblePressure {
            get {
                return ResourceManager.GetString("ContextEffectDribblePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing ContextEffectKickAngle made it very difficult to play the AI (as a poor team). The ability of players meant more, the game was slower too.
        /// </summary>
        internal static string ContextEffectKickAngle {
            get {
                return ResourceManager.GetString("ContextEffectKickAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increasing ContextEffectPressure caused more interceptions, less dependant on ability.
        ///Raising this caused a lesser team to beat a bigger team easily.
        /// </summary>
        internal static string ContextEffectPressure {
            get {
                return ResourceManager.GetString("ContextEffectPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By saving this file using this tool, you agree to not share it without attribution to me &quot;paulv2k4&quot; with a link to my patreon https://www.patreon.com/fifa_gameplay_career_mod or website https://v2k4fifamodding.azurewebsites.net/.
        ///
        ///Do you agree to this and wish to overwrite your locale.ini?.
        /// </summary>
        internal static string SaveOverOldLocaleINIText {
            get {
                return ResourceManager.GetString("SaveOverOldLocaleINIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the AI to do keepy uppy tricks.
        /// </summary>
        internal static string TakePissMiniDesc {
            get {
                return ResourceManager.GetString("TakePissMiniDesc", resourceCulture);
            }
        }
    }
}
